substitutions:
  devicename: m5stick-atom-bedroom
  upper_devicename: Bedroom

esphome:
  name: $devicename

packages:
  base: !include common/base.yaml

# https://docs.m5stack.com/en/core/atom_lite
esp32:
  board: m5stack-atom
  framework:
    type: arduino
i2c:
  sda: 26
  scl: 32
  scan: true

sensor:
  # https://docs.m5stack.com/en/unit/co2
  # https://esphome.io/components/sensor/scd4x.html
  - platform: scd4x
    address: 0x62
    update_interval: 60s
    co2:
      name: "${upper_devicename} CO2"
    temperature:
      name: "${upper_devicename} Temperature"
    humidity:
      name: "${upper_devicename} Humidity"
