substitutions:
  devicename: m5stick-atom-bedroom
  upper_devicename: Bedroom

esphome:
  name: $devicename

packages:
  base: !include common/base.yaml

# https://docs.m5stack.com/en/core/atom_lite
esp32:
  board: m5stack-atom
  framework:
    type: arduino

i2c:
  sda: 26
  scl: 33
  scan: true
# https://docs.m5stack.com/en/unit/co2
# https://esphome.io/components/sensor/scd4x.html

