substitutions:
  devicename: m5stick-atom-bedroom
  upper_devicename: Bedroom

esphome:
  name: $devicename

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${upper_devicename} Fallback
    password: !secret wifi_password

captive_portal:
