# https://github.com/apolselli/home-assistant-config/blob/master/esphome/m5stickc_env.yaml
substitutions:
  devicename: m5stickcplus-kitchen
  upper_devicename: Kitchen

esphome:
  name: $devicename

esp32:
  board: m5stick-c
  framework:
    type: arduino

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  ap:
    ssid: ${upper_devicename} Fallback
    password: !secret wifi_password

logger:

api:

ota:

web_server:

captive_portal:

i2c:
  - id: hat
    sda: 0
    scl: 26
    scan: true
  - id: bottom
    sda: 32
    scl: 33
    scan: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: ${upper_devicename} Button A
    on_press:
      then:
        - switch.toggle: led1
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${upper_devicename} Button B
    on_press:
      then:
        - switch.toggle: led1

sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
  - platform: uptime
    name: ${upper_devicename} Uptime

  # https://docs.m5stack.com/en/hat/hat_envIII
  # https://esphome.io/components/sensor/sht3xd.html
  - platform: sht3xd
    i2c_id: hat
    address: 0x44
    update_interval: 60s
    temperature:
      name: ${upper_devicename} SHT30 Temperature
    humidity:
      name: ${upper_devicename} SHT30 Humidity

  # https://esphome.io/components/sensor/qmp6988.html
  - platform: qmp6988
    i2c_id: hat
    address: 0x70
    update_interval: 60s
    temperature:
      name: ${upper_devicename} QMP6988 Temperature
    pressure:
      name: ${upper_devicename} QMP6988 Pressure
    iir_filter: 2x

  # https://docs.m5stack.com/en/unit/tvoc
  # https://esphome.io/components/sensor/sgp30.html
  - platform: sgp30
    i2c_id: bottom
    address: 0x58
    update_interval: 60s
    eco2:
      name: ${upper_devicename} SGP30 eCO2
      accuracy_decimals: 1
    tvoc:
      name: ${upper_devicename} SGP30 TVOC
      accuracy_decimals: 1
    store_baseline: yes

switch:
  - platform: restart
    name: ${upper_devicename} Restart
  - platform: gpio
    pin:
      number: GPIO10
      inverted: true
    name: ${upper_devicename} Led
    id: led1
