substitutions:
  devicename: m5stickcplus-kitchen
  friendly_name: Kitchen

esphome:
  name: $devicename

packages:
  base: !include common/base.yaml

# https://docs.m5stack.com/en/core/m5stickc_plus
esp32:
  board: m5stick-c
  framework:
    type: arduino

i2c:
  - id: hat
    sda: 0
    scl: 26
    scan: true
  - id: bottom
    sda: 32
    scl: 33
    scan: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: ${friendly_name} Button A
    on_press:
      then:
        - switch.toggle: led1
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${friendly_name} Button B
    on_press:
      then:
        - switch.toggle: led1

sensor:
  # https://docs.m5stack.com/en/hat/hat_envIII
  # https://esphome.io/components/sensor/sht3xd.html
  - platform: sht3xd
    i2c_id: hat
    address: 0x44
    update_interval: 60s
    temperature:
      name: ${friendly_name} SHT30 Temperature
    humidity:
      name: ${friendly_name} SHT30 Humidity

  # https://esphome.io/components/sensor/qmp6988.html
  - platform: qmp6988
    i2c_id: hat
    address: 0x70
    update_interval: 60s
    temperature:
      name: ${friendly_name} QMP6988 Temperature
    pressure:
      name: ${friendly_name} QMP6988 Pressure
    iir_filter: 2x

  # https://docs.m5stack.com/en/unit/tvoc
  # https://esphome.io/components/sensor/sgp30.html
  - platform: sgp30
    i2c_id: bottom
    address: 0x58
    update_interval: 60s
    eco2:
      name: ${friendly_name} SGP30 eCO2
      accuracy_decimals: 1
    tvoc:
      name: ${friendly_name} SGP30 TVOC
      accuracy_decimals: 1
    store_baseline: yes

switch:
  - platform: gpio
    pin:
      number: GPIO10
      inverted: true
    name: ${friendly_name} Led
    id: led1
