esphome:
  name: kitchen
  includes:
    - my_custom_sensor.h

# Example configuration entry
sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new MyCustomSensor();
      App.register_component(my_sensor);
      return {my_sensor};

    sensors:
      name: "My Custom Sensor"

esp32:
  board: m5stick-c
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $devicename Fallback Hotspot
    password: !secret iot_wifi_pwd

captive_portal:
